app/course/__init__.py
from flask import Blueprint

courses = Blueprint('courses', __name__)

from . import views

app/course/views.py
from flask import render_template, redirect, url_for, make_response, session, request, Response
from flask_login import login_user, logout_user, current_user, login_required
from flask import current_app

from . import courses
from ..models import Course, Lesson, Video, db, UserFavorite


@courses.route('/list/')
def course_list():
    page = request.args.get('page', 1, type=int)
    sort = request.args.get('sort', 'new', type=str)
    if sort == 'new':
        pagination = Course.query.order_by(Course.add_time.desc()).paginate(page, per_page=12, error_out=False)
    elif sort == 'hot':
        pagination = Course.query.order_by(Course.click_nums.desc()).paginate(page, per_page=12, error_out=False)
    elif sort == 'join':
        pagination = Course.query.order_by(Course.students.desc()).paginate(page, per_page=12, error_out=False)
    else:
        pagination = Course.query.order_by(Course.add_time.desc()).paginate(page, per_page=12, error_out=False)
    recommend_course = Course.query.order_by(Course.click_nums.desc()).filter_by(recommend=True)
    if recommend_course:
        recommend_course = recommend_course[:3]
    return render_template(
        'course/course-list.html',
        pagination=pagination,
        sort=sort,
        recommend_course=recommend_course
    )


@courses.route('/detail/<int:course_id>')
def course_detail(course_id):
    course = Course.query.get_or_404(int(course_id))
    if not current_user.is_anonymous:
        current_user.courses.append(course)
        db.session.add(current_user)
        db.session.commit()
    if current_user.is_anonymous:
        course_has_fav = False
        org_has_fav = False
    else:
        course_has_fav = UserFavorite.query.filter_by(fav_type=0, fav_id=course.id, user_id=current_user.id).first()
        org_has_fav = UserFavorite.query.filter_by(fav_type=1, fav_id=course.courseorg_id, user_id=current_user.id).first()
    # 相关课程推荐
    # recommend_courses = Course.query.filter_by(recommend=True,)
    return render_template(
        'course/course-detail.html',
        course=course,
        course_has_fav=course_has_fav,
        org_has_fav=org_has_fav,
    )


@courses.route('/section/<int:course_id>')
@login_required
def course_section(course_id):
    course = Course.query.get_or_404(int(course_id))
    return render_template(
        'course/course-video.html',
        course=course,
    )


@courses.route('/section/<int:course_id>/video/<int:video_id>')
@login_required
def course_video(course_id, video_id):
    course = Course.query.get_or_404(int(course_id))
    videos = Video.query.get_or_404(int(video_id))
    return render_template(
        'course/course-play.html',
        videos=videos,
        course=course,
    )

app/templates/course/course-detail.html
{% extends 'base.html' %}
{% block title %}课程详情 - 在线教育 {% endblock %}

{% block nav_path %}
    <section>
    <div class="wp">
        <div class="crumbs">
            <ul>
                <li><a href="{{ url_for('index.index') }}">首页</a>></li>
                <li><a href="{{ url_for('courses.course_list') }}">课程</a>></li>
                <li>课程详情</li>
            </ul>
        </div>
    </div>
</section>
{% endblock %}

{% block comment %}

<section>
    <div class="wp">
        <div class="groupPurchase_detail detail">
            <div class="toppro">
                <div class="left">
                    <div class="picbox">
                        <div class="tb-booth tb-pic">
                            <img width="440" height="445"
                                 src="{% if course.image %}{{ url_for('static',filename=course.image) }}{% else %}{% endif %}"
                                 class="jqzoom"/>
                        </div>

                    </div>
                    <div class="des">
                        <h1 title="{{ course.name }}">{{ course.name }}</h1>
                        <span class="key">{{ course.desc }}</span>
                        <div class="prize">
                            <span class="fl">难度：<i class="key">{{ course.get_degree }}</i></span>
                            <span class="fr">学习人数：{{ course.students }}</span>
                        </div>
                        <ul class="parameter">
                            <li><span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span>{{ course.learn_time }}</span></li>
                            <li><span class="pram word3">章&nbsp;节&nbsp;数：</span><span>{{ course.lessions|length }}</span></li>
                            <li><span class="pram word3">课程类别：</span><span title="">{{ course.category }}</span></li>
                            <li class="piclist"><span class="pram word4">学习用户：</span>

                                <span class="pic"><img width="40" height="40"
                                                       src="{{ url_for('static',filename='media/image/2016/12/default_big_14.png') }}"/></span>

                            </li>
                        </ul>
                        <div class="btns">
                            <div class="btn colectgroupbtn" id="jsLeftBtn">
                                {% if course_has_fav %}已收藏{% else %}收藏{% endif %}
                            </div>
                            <div class="buy btn"><a style="color: white" href="{{ url_for('courses.course_section',course_id=course.id) }}">开始学习</a></div>
                        </div>
                    </div>
                    <div class="group-share-box">
                        <div class="bdsharebuttonbox"
                             data-text="django开始了"
                             data-desc="我在#慕课网#发现了"
                             data-comment=""
                             data-url="/group/groupdetail/15/">
                            <span class="fl">分享到：</span>
                            <a href="#" class="bds_more" data-cmd="more"></a>
                            <a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a>
                            <a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a>
                            <a title="分享到腾讯微博" href="#" class="bds_tqq" data-cmd="tqq"></a>
                            <a title="分享到人人网" href="#" class="bds_renren" data-cmd="renren"></a>
                            <a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a>
                        </div>
                    </div>
                </div>
                <div class="right">
                    <div class="head">
                        <h1>授课机构</h1>
                        <p>世界名校，课程权威</p>
                    </div>
                    <div class="pic">
                        <a href="{{ url_for('org.org_detail_page',org_id=course.courseorg.id) }}">
                            <img width="150" height="80" src="{{ url_for('static',filename=course.courseorg.image) }}"/>
                        </a>
                    </div>
                    <a href="{{ url_for('org.org_detail_page',org_id=course.courseorg.id) }}">
                        <h2 class="center" title="{{ course.courseorg.name }}">{{ course.courseorg.name }}</h2>
                    </a>
                    <div class="btn  notlogin
					     " data-favid="14" id="jsRightBtn">
                        {% if org_has_fav %}已收藏{% else %}收藏{% endif %}
                    </div>
                    <div class="clear">
                        <ul>
                            <li>
                                <span>课 &nbsp;程&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   {{ course.courseorg.courses|length }}</span>
                            </li>
                            <li>
                                <span>教 &nbsp;师&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{ course.courseorg.teachers|length }}</span>
                            </li>
                            <li>所在地区：&nbsp;&nbsp;{{ course.courseorg.address }}</li>
                            <li>认&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;证&nbsp;:
                                &nbsp;&nbsp;
                                <img title="金牌机构" , src="{{ url_for('static',filename='images/gold.png') }}"/>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="wp">
        <div class="list groupPurchase_detail_pro">
            <div class="left layout">
                <div class="head">
                    <ul class="tab_header">
                        <li class="active">课程详情</li>
                    </ul>
                </div>
                <div class="tab_cont tab_cont1">
                    {{ course.detail|safe }}
                </div>
                <div class="tab_cont tab_cont2">
                    <div class="comment">
                        <div class="comenlist">

                        </div>
                    </div>
                </div>
            </div>
            <div class="right layout">
                <div class="head">相关课程推荐</div>
                <div class="group_recommend">

                    <dl>
                        <dt>
                            <a target="_blank" href="">
                                <img width="240" height="220" class="scrollLoading"
                                     src=""/>
                            </a>
                        </dt>
                        <dd>
                            <a target="_blank" href=""><h2></h2></a>
                            <span class="fl">学习时长：<i class="key">0</i></span>
                        </dd>
                    </dl>

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block extend_js %}
    <script type="text/javascript">
        //收藏分享
        function add_fav(current_elem, fav_id, fav_type) {
            $.ajax({
                cache: false,
                type: "POST",
                url: "{{ url_for('users.add_user_collect') }}",
                data: {'fav_id': fav_id, 'fav_type': fav_type},
                async: true,
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token() }}");
                },
                success: function (data) {
                    if (data.status == 'failed') {
                        if (data.msg == '用户未登录') {
                            window.location.href = "{{ url_for('auth.login') }}";
                        } else {
                            alert(data.msg)
                        }

                    } else if (data.status == 'success') {
                        current_elem.text(data.msg)
                    }
                },
            });
        }

        $(document).ready(function () {
            $('#jsLeftBtn').on('click', function () {
                add_fav($(this), {{ course.id }}, 0);
            });
        });

        $(document).ready(function () {
            $('#jsRightBtn').on('click', function () {
                add_fav($(this), {{ course.courseorg.id }}, 1);
            });
        });

    </script>

{% endblock %}

app/templates/course/course-list.html
{% extends 'base.html' %}
{% block title %}课程列表 - 在线教育{% endblock %}

{% block nav_path %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{{ url_for('index.index') }}">首页</a>></li>
                <li>课程</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block comment %}
    <section>
        <div class="wp">
            <div class="list" style="margin-top:0;">
                <div class="left layout">
                    <div class="head">
                        <ul class="tab_header">
                            <li class="{% if sort=='new' or sort=='' %}active{% else %}{% endif %}"><a
                                    href="{{ url_for('courses.course_list',page=pagination.page,sort='new') }}">最新 </a>
                            </li>
                            <li class="{% if sort=='hot' %}active{% else %}{% endif %}">
                                <a href="{{ url_for('courses.course_list',page=pagination.page,sort='hot') }}">最热门</a>
                            </li>
                            <li class="{% if sort=='join' %}active{% else %}{% endif %}">
                                <a href="{{ url_for('courses.course_list',page=pagination.page,sort='join') }}">参与人数</a>
                            </li>
                        </ul>
                    </div>
                    <div id="inWindow">
                        <div class="tab_cont " id="content">
                            <div class="group_list">
                                {% for course in pagination.items %}
                                    <div class="box">
                                        <a href="{{ url_for('courses.course_detail',course_id=course.id) }}">
                                            <img width="280" height="350" class="scrollLoading"
                                                 src="{% if course.image %}{{ url_for('static',filename=course.image) }}{% else %}{% endif %}"/>
                                        </a>
                                        <div class="des">
                                            <a href="{{ url_for('courses.course_detail',course_id=course.id) }}">
                                                <h2>{{ course.name }}</h2>
                                            </a>
                                            <span class="fl">时长：<i class="key">{{ course.leran_time }}</i></span>
                                            <span class="fr">学习人数：{{ course.students }}&nbsp;&nbsp;</span>
                                        </div>
                                        <div class="bottom">
                                            <a href="{{ url_for('courses.course_detail',course_id=course.id) }}"><span
                                                    class="fl">{{ course.courseorg.name }}</span></a>
                                            <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ course.fav_nums }}
                                    </span>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="pageturn">
                                <ul class="pagelist">
                                    <li class="long" style="display:{% if pagination.has_prev %}block{% else %}none{% endif %}">
                                        <a href="{{ url_for('courses.course_list',page=pagination.page - 1,sort=sort) }}">上一页</a>
                                    </li>
                                    {% for p in pagination.iter_pages() %}
                                        {% if p %}
                                            {% if p==pagination.page %}
                                                <li class="active">
                                                    <a href="{{ url_for('courses.course_list',page=p,sort=sort) }}">{{ p }}</a>
                                                </li>
                                            {% else %}
                                                <li>
                                                    <a href="{{ url_for('courses.course_list',page=p,sort=sort) }}">{{ p }}</a>
                                                </li>
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                    <li class="long"
                                        style="display:{% if pagination.has_next %}block{% else %}none{% endif %}">
                                        <a href="{{ url_for('courses.course_list',page=pagination.page + 1,sort=sort) }}">下一页</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="right layout">
                    <div class="head">热门课程推荐</div>
                    <div class="group_recommend">
                        {% for course in recommend_course %}
                            <dl>
                                <dt>
                                    <a target="_blank" href="">
                                        <img width="240" height="220" class="scrollLoading"
                                             src="{% if course.image %}{{ url_for('static',filename=course.image) }}{% else %}{% endif %}"/>
                                    </a>
                                </dt>
                                <dd>
                                    <a target="_blank" href=""><h2>{{ course.name }}</h2></a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree }}</i></span>
                                </dd>
                            </dl>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

app/templates/course/course-play.html
{% extends 'course/course-video.html' %}
{% block title %}课程视频信息 - 在线教育{% endblock %}

{% block extend_css %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static',filename='js/video.min.js') }}"></script>
    <style>
        .video-js .vjs-big-play-button {
            top: 50%;
            left: 50%;
        }
    </style>
{% endblock %}

<!--crumbs start-->
{% block comment %}
    {{ super() }}
    {% block play_video %}
    <div style="width:1200px;height:675px; margin-left: 0px">
        <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="1200"
               poster="http://video-js.zencoder.com/oceans-clip.png"
               data-setup="{}">
            <source src="{{ url_for('static',filename=videos.path) }}"
                    type='video/mp4'>
        </video>
    </div>
    {% endblock %}
{% endblock %}

app/templates/course/course-video.html
{% extends 'base.html' %}
{% block title %}课程视频信息 - 在线教育{% endblock %}

{% block extend_css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/muke/base.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/muke/common-less.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/muke/course/learn-less.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/aui.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/mooc.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/muke/course/common-less.css') }}">
{% endblock %}

{% block nav_path %}
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="{{ url_for('index.index') }}">首页</a>></li>
                    <li><a href="{{ url_for('courses.course_list') }}">课程</a>></li>
                    <li><a href="{{ url_for('courses.course_detail',course_id=course.id) }}">课程详情</a>></li>
                    <li>章节信息</li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}


{% block comment %}
<div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_time }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>1{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                {% block play_video %}
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active active" id="learnOn"
                                   href="course-video.html"><span>章节</span></a></li>
                            <li><a id="commentOn" class="" href="course-comment.html"><span>评论</span></a></li>
                        </ul>
                    </div>
                    <div id="notice" class="clearfix">
                        <div class="l"><strong>课程公告:</strong> <a href="javascript:void(0)">{{ course.notice }}</a>
                        </div>
                    </div>

                    <div class="mod-chapters">
                    {% for lesson in course.lessons %}
                        <div class="chapter chapter-active">
                            <h3>
                                <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                            </h3>
                            <ul class="video">
                                {% for video in lesson.videos %}
                                <li>
                                    <a target="_blank"
                                       href='{{ url_for('courses.course_video',video_id=video.id,course_id=course.id) }}'
                                       class="J-media-item studyvideo">{{ video.name }}
                                        <i class="study-state"></i>
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endfor %}
                    </div>

                </div>
                {% endblock %}
                <div class="aside r">
                    <div class="bd">

                        <div class="box mb40">
                            <h4>资料下载</h4>
                            <ul class="downlist">

                                <li>
                                    <span><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;资料</span>
                                    <a href="{{ url_for('static',filename=course.resources.download) }}" class="downcode"
                                       target="_blank" download="" data-id="274" title="">下载</a>
                                </li>

                            </ul>
                        </div>
                        <div class="box mb40">
                            <h4>讲师提示</h4>
                            <div class="teacher-info">
                                <a href="/u/315464/courses?sort=publish" target="_blank">
                                    <img src='' width='80' height='80'/>
                                </a>
                                <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                                <span class="job">xxx</span>
                            </div>
                            <div class="course-info-tip">
                                <dl class="first">
                                    <dt>课程须知</dt>
                                    <dd class="autowrap">{{ course.youneed_know }}</dd>
                                </dl>
                                <dl>
                                    <dt>老师告诉你能学到什么？</dt>
                                    <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                </dl>
                            </div>
                        </div>


                        <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                     style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">

                                        <li class="curr">
                                            <a href="course-detail.html" target="_blank">
                                                <img src="../media/courses/2016/11/540e57300001d6d906000338-240-135_n0L8vbw.jpg"
                                                     alt="django与vuejs实战项目2">
                                                <span class="name autowrap">django与vuejs实战项目2</span>
                                            </a>
                                        </li>

                                        <li class="curr">
                                            <a href="course-detail.html" target="_blank">
                                                <img src="../media/courses/2016/12/python面向对象.jpg" alt="python面向对象">
                                                <span class="name autowrap">python面向对象</span>
                                            </a>
                                        </li>

                                        <li class="curr">
                                            <a href="course-detail.html" target="_blank">
                                                <img src="../media/courses/2016/12/python文件处理.jpg" alt="python文件处理">
                                                <span class="name autowrap">python文件处理</span>
                                            </a>
                                        </li>

                                        <li class="curr">
                                            <a href="course-detail.html" target="_blank">
                                                <img src="../media/courses/2016/11/mysql.jpg" alt="django入门">
                                                <span class="name autowrap">django入门</span>
                                            </a>
                                        </li>

                                        <li class="curr">
                                            <a href="course-detail.html" target="_blank">
                                                <img src="../media/courses/2016/12/mysql.jpg" alt="xadmin进阶开发">
                                                <span class="name autowrap">xadmin进阶开发</span>
                                            </a>
                                        </li>

                                    </ul>
                                </div>
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg"
                                                     alt="Java工程师">
                                                <span class="name autowrap">Java工程师</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
</div>
{% endblock %}