app/users/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, Email, ValidationError, Length, EqualTo
from wtforms import StringField, SubmitField, PasswordField, BooleanField, DateField
from flask_wtf.file import FileField, FileAllowed, FileRequired
from flask_login import current_user
from datetime import datetime, timedelta

from app.models import User, EmailVerifyCode
from app import db


class UserInfoForm(FlaskForm):
    nick_name = StringField('用户名', validators=[DataRequired()], render_kw={"placeholder": "用户名"})
    address = StringField('用户地址', validators=[], render_kw={"placeholder": "请输入你的地址"})
    email = StringField('用户邮箱', validators=[Email()], )
    mobile = StringField('手机号码', validators=[DataRequired()], )
    gender = StringField('性别', validators=[DataRequired()], )
    birthday = DateField('生日日期', validators=[DataRequired()], )
    submit = SubmitField('保存')

    def validate_nick_name(self, field):
        result = self.get_user()
        if result is False:
            raise ValidationError('用户已存在')

    def get_user(self):
        ret1 = User.query.filter(User.id.notin_([current_user.id, ])).filter_by(username=self.nick_name.data).first()
        if ret1:
            return False
        else:
            return True

    def save(self):
        current_user.username = self.nick_name.data
        current_user.address = self.address.data
        current_user.email = self.email.data
        current_user.gender = self.gender.data
        current_user.birthday = self.birthday.data
        current_user.mobile = self.mobile.data
        db.session.add(current_user)
        db.session.commit()


class UpdateEmailForm(FlaskForm):
    email = StringField('用户邮箱', validators=[Email()], )
    code = StringField('邮箱验证码', validators=[DataRequired()], )
    submit = SubmitField('submit')

    def validate_email(self, field):
        result = self.get_user()
        if result is False:
            raise ValidationError('邮箱已存在')

    def get_user(self):
        ret = User.query.filter_by(email=self.email.data).first()
        if ret:
            return False
        else:
            return True

    def save(self):  # 当前时间前60秒内的验证码有效
        verify_code = EmailVerifyCode.query.filter(EmailVerifyCode.add_time >=
                                                   (datetime.now() - timedelta(seconds=60))) \
            .filter_by(code_type='2', code=self.code.data, email=self.email.data, ).first()
        if verify_code:
            current_user.email = self.email.data
            db.session.add(current_user)
            db.session.commit()


class UpdatePassword(FlaskForm):
    password1 = PasswordField('新密码', validators=[DataRequired(), EqualTo('password2', "两次密码不一致")])
    password2 = PasswordField('确认新密码', validators=[DataRequired()])

    def save(self):
        current_user.password = self.password1.data
        db.session.add(current_user)
        db.session.commit()


class UpdateHeadIcon(FlaskForm):
    image = FileField('头像', validators=[FileRequired()])

app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from . import views

app/users/views.py
from flask import render_template, redirect, url_for, make_response, session, request, Response, jsonify
from flask_login import login_user, logout_user, current_user, login_required
from flask import current_app
from werkzeug.utils import secure_filename
import os

from . import users
from ..models import User, Course, UserFavorite, Teacher, CourseOrg, db, EmailVerifyCode
from ..utils.utils import Pagination, random_verify_code
from .forms import UserInfoForm, UpdateEmailForm, UpdatePassword, UpdateHeadIcon
from ..email import send_verify_code
from config import basedir

static_dir = os.path.join(basedir, 'app', 'static')


@users.route('/info/', methods=['GET', 'POST'])
@login_required
def user_info():
    form = UserInfoForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            response = make_response(jsonify({"status": "success"}))
            form.save()
        else:
            response = make_response(jsonify({"status": "failure", "msg": form.errors}))
        response.headers['Access-Control-Allow-Origin'] = '*'
        return response
    return render_template(
        'users/usercenter-info.html',
    )


@users.route('/courses/')
@login_required
def user_courses():
    page = request.args.get('page', 1, type=int)
    total_courses = current_user.courses
    pagination = Pagination(page=page, per_page=8, items=total_courses)
    return render_template(
        'users/usercenter-mycourse.html',
        pagination=pagination,
    )


@users.route('/collects/orgs/')
@login_required
def user_collects_orgs():  # 我收藏的机构
    """
        ('1', '机构'),
    """
    page = request.args.get('page', 1, type=int)
    user_favorites = UserFavorite.query.filter_by(fav_type=1, user_id=current_user.id)
    fav_list = []
    if user_favorites:
        for elem in user_favorites:
            query_object = CourseOrg.query.get_or_404(elem.fav_id)
            fav_list.append(query_object)
    pagination = Pagination(page=page, per_page=6, items=fav_list)
    return render_template(
        'users/usercenter-fav-org.html',
        pagination=pagination,
    )


@users.route('/collects/teachers/')
@login_required
def user_collects_teachers():  # 我收藏的讲师
    """
        ('2', '讲师'),
    """
    page = request.args.get('page', 1, type=int)
    user_favorites = UserFavorite.query.filter_by(fav_type=2, user_id=current_user.id)
    fav_list = []
    if user_favorites:
        for elem in user_favorites:
            query_object = Teacher.query.get_or_404(elem.fav_id)
            fav_list.append(query_object)
    pagination = Pagination(page=page, per_page=6, items=fav_list)
    return render_template(
        'users/usercenter-fav-teacher.html',
        pagination=pagination,
    )


@users.route('/collects/courses/')
@login_required
def user_collects_courses():  # 我收藏的课程
    """ ('0', '课程'),
    """
    page = request.args.get('page', 1, type=int)
    user_favorites = UserFavorite.query.filter_by(fav_type=0, user_id=current_user.id)
    fav_list = []
    if user_favorites:
        for elem in user_favorites:
            query_object = Course.query.get_or_404(elem.fav_id)
            fav_list.append(query_object)
    pagination = Pagination(page=page, per_page=6, items=fav_list)
    return render_template(
        'users/usercenter-fav-course.html',
        pagination=pagination,
    )


@users.route('/messages/')
@login_required
def user_messages():
    page = request.args.get('page', 1, type=int)
    messages = current_user.messages
    pagination = Pagination(page=page, per_page=8, items=messages)
    for message in pagination.get_items:
        message.has_read = True
        db.session.add(message)
    db.session.commit()
    return render_template(
        'users/usercenter-message.html',
        pagination=pagination,
    )


@users.route('/add_collect/', methods=['POST', ])
@login_required
def add_user_collect():
    """
        ('0', '课程'),
        ('1', '机构'),
        ('2', '讲师'),
    """
    if request.method == 'POST':
        if not current_user.is_authenticated:
            response = make_response(jsonify({"status": "failed", "msg": "用户未登录"}))
            response.headers['Access-Control-Allow-Origin'] = '*'
            return response
        fav_id = request.values.get('fav_id')
        fav_type = request.values.get('fav_type')
        fav_record = UserFavorite.query.filter_by(fav_type=fav_type, fav_id=fav_id).first()
        if fav_record:
            db.session.delete(fav_record)
            # 计算收藏数量
            response = make_response(jsonify({"status": "success", "msg": "收藏"}))
            if int(fav_type) == 0:
                fav_object = Course.query.get_or_404(fav_id)
                fav_object.fav_nums -= 1
            elif int(fav_type) == 1:
                fav_object = CourseOrg.query.get_or_404(fav_id)
                fav_object.fav_nums -= 1
            elif int(fav_type) == 2:
                fav_object = Teacher.query.get_or_404(fav_id)
                fav_object.fav_nums -= 1
            db.session.add(fav_object)
        else:
            user_fav = UserFavorite(fav_id=fav_id, fav_type=fav_type, user_id=current_user.id)
            db.session.add(user_fav)
            if int(fav_type) == 0:
                fav_object = Course.query.get_or_404(fav_id)
                fav_object.fav_nums += 1
            elif int(fav_type) == 1:
                fav_object = CourseOrg.query.get_or_404(fav_id)
                fav_object.fav_nums += 1
            elif int(fav_type) == 2:
                fav_object = Teacher.query.get_or_404(fav_id)
                fav_object.fav_nums += 1
            db.session.add(fav_object)
            response = make_response(jsonify({"status": "success", "msg": "已收藏"}))
        db.session.commit()
        response.headers['Access-Control-Allow-Origin'] = '*'
        return response


@users.route('/update_head_icon/', methods=['POST'])
@login_required
def update_head_icon():
    form = UpdateHeadIcon()
    if form.validate_on_submit():
        f = form.image.data
        filename = secure_filename(f.filename)
        upload_dir = os.path.join(static_dir, 'media/uploadFile/user', str(current_user.id))
        print(upload_dir)
        if not os.path.isdir(upload_dir):
            os.makedirs(upload_dir)
        f.save(os.path.join(upload_dir, filename))
        current_user.image = 'media/uploadFile/user' + '/' + str(current_user.id) + '/' + filename
        db.session.add(current_user)
        db.session.commit()
        response = make_response(jsonify({"status": "success"}))
    else:
        response = make_response(jsonify({"status": "failed", "msg": form.errors.get('image')}))
    response.headers['Access-Control-Allow-Origin'] = '*'
    return response


@users.route('/update_password/', methods=['POST'])
@login_required
def update_user_password():
    form = UpdatePassword()
    if form.validate_on_submit():
        form.save()
        response = make_response(jsonify({"status": "success"}))
    else:
        response = make_response(jsonify({"status": "failed", "msg": form.errors.get('password1')}))
    response.headers['Access-Control-Allow-Origin'] = '*'
    return response


@users.route('/update_email/', methods=['POST'])
@login_required
def update_user_email():
    form = UpdateEmailForm()
    if form.validate_on_submit():
        form.save()
        response = make_response(jsonify({"status": "success", "msg": "已收藏"}))
    else:
        response = make_response(jsonify({"email": form.errors}))
    response.headers['Access-Control-Allow-Origin'] = '*'
    return response


@users.route('/send_email_code/')
@login_required
def send_email_code():
    email = request.args.get('email', type=str)
    if email is None:
        response = make_response(jsonify({'email': '邮箱不能为空'}))
        response.headers['Access-Control-Allow-Origin'] = '*'
        return response
    result = User.query.filter_by(email=email).first()
    if result:
        response = make_response(jsonify({'email': '邮箱已存在'}))
    else:
        templates = dict()
        code = random_verify_code()
        templates['code'] = code
        templates['username'] = current_user.username
        send_verify_code(email, '修改邮箱', templates, send_type='update_email')
        record = EmailVerifyCode()
        record.email = email
        record.code = code
        record.code_type = '2'
        db.session.add(record)
        db.session.commit()
        response = make_response(jsonify({'status': 'success'}))
    response.headers['Access-Control-Allow-Origin'] = '*'
    return response

app/templates/users/usercenter-fav-course.html
{% extends 'users/usercenter-fav-org.html' %}
{% block collect_block %}
    <div class="companycenter">
        <div class="group_list brief">
            {% for elem in pagination.get_items %}
            <div class="module1_5 box">
                <a href="{{ url_for('courses.course_detail',course_id=elem.id) }}">
                    <img width="214" height="190" src="{{ url_for('static',filename=elem.image) }}"/>
                </a>
                <div class="des">
                    <a href="{{ url_for('courses.course_detail',course_id=elem.id) }}"><h2>{{ elem.name }}</h2></a>
                    <span class="fl">时长：<i class="key">{{ elem.learn_time }}</i></span>
                    <span class="fr">学习人数：{{ elem.students }}</span>
                </div>
                <div class="bottom">
                    <span class="fl">{{ elem.courseorg.name }}</span>
                    <span class="delete-group fr jsDeleteFav_course" data-favid="{{ elem.id }}"></span>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/users/usercenter-fav-org.html
{% extends 'users/user_base.html' %}
{% block title %}个人中心 - 我的收藏{% endblock %}

{% block nav_path %}

    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{{ url_for('index.index') }}">首页</a>></li>
                <li><a href="{{ url_for('users.user_info') }}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_block %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="{% if request.endpoint=='users.user_collects_orgs' %}active{% else %}{% endif %}"><a href="{{ url_for('users.user_collects_orgs',page=pagination.page) }}">课程机构</a> </li>
                        <li class="{% if request.endpoint=='users.user_collects_teachers' %}active{% else %}{% endif %}"><a href="{{ url_for('users.user_collects_teachers',page=pagination.page) }}">授课教师 </a></li>
                        <li class="{% if request.endpoint=='users.user_collects_courses' %}active{% else %}{% endif %}"><a href="{{ url_for('users.user_collects_courses',page=pagination.page) }}">公开课程</a></li>
                    </ul>
                </div>
                {% block collect_block %}
                <div class="messagelist">
                    {% for elem in pagination.get_items %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{{ url_for('org.org_detail_page',org_id=elem.id) }}">
                                    <img width="160" height="90" src="{{ url_for('static',filename=elem.image) }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{{ url_for('org.org_detail_page',org_id=elem.id) }}">{{ elem.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{{ url_for('static',filename='images/authentication.png') }}"/>


                                    <img src="{{ url_for('static',filename='images/gold.png') }}"/>

                                </div>
                                <span class="c8 clear">{% if elem.address %}{{ elem.address }}{% else %}{% endif %}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ elem.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
                {% endblock %}
            </div>
        </div>
{% endblock %}

app/templates/users/usercenter-fav-teacher.html
{% extends 'users/usercenter-fav-org.html' %}
{% block collect_block %}
    <div class="messagelist">
    {% for elem in pagination.get_items %}
    <div class=" butler_list butler-fav-box">
        <dl class="des users">
            <dt>
                <a href="{{ url_for('org.teacher_detail',teacher_id=elem.id) }}">
                    <img width="100" height="100" src="{{ url_for('static',filename=elem.image) }}"/>
                </a>
            </dt>
            <dd>
                <h1>
                    <a href="{{ url_for('org.teacher_detail',teacher_id=elem.id) }}">
                        {{ elem.name }}<span class="key">认证教师</span>
                    </a>
                </h1>
                <ul class="cont clearfix">
                    <li class="time">工作年限：<span>{{ elem.work_years }}年</span></li>
                    <li class="c7">课程数：<span>{{ elem.courses|length }}</span></li>
                </ul>
                <ul class="cont clearfix">
                    <li class="time">工作公司：<span>{% if elem.work_company %}{{ elem.work_company }}{% else %}暂无信息{% endif %}</span></li>
                    <li class="c7">公司职位：<span>{% if elem.work_position %}{{ elem.work_position }}{% else %}暂无信息{% endif %}</span></li>
                </ul>
            </dd>
            <div class="delete jsDeleteFav_teacher" data-favid="{{ elem.id }}"></div>
        </dl>
    </div>
    {% endfor %}
    </div>
{% endblock %}

app/templates/users/usercenter-info.html
{% extends 'users/user_base.html' %}

<!--crumbs start-->
{% block nav_path %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{{ url_for('index.index') }}">首页</a>></li>
                <li><a href="#">个人中心</a>></li>
                <li>个人资料</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_block %}
    <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人信息</h1>
			</div>
			<div class="inforcon">
				<div class="left" style="width:242px;">
                    <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{{ url_for('users.update_head_icon') }}" target='frameFile'>
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="{% if current_user.image %}{{ url_for('static',filename=current_user.image) }}{% else %}{% endif %}"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                            </span>
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                        </label>
                    </form>
                    <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                        <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                    </div>
				</div>
				<form class="perinform" id="jsEditUserForm" autocomplete="off">
					<ul class="right">
						<li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                           <input type="text" name="nick_name" id="nick_name" value="{{ current_user.name }}" maxlength="10">
                            <i class="error-tips"></i>
                        </li>
						<li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                           <input type="text" id="birth_day" name="birthday" value="{{ current_user.birthday }}" readonly="readonly"/>
                            <i class="error-tips"></i>
						</li>
						<li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
                            <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="0"
                                                                        {% if current_user.gender=='0' %}checked="checked"{% else %}{% endif %}>男</label>
                            <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="1"
                                                                              {% if current_user.gender=='1' %}checked="checked"{% else %}{% endif %}>女</label>
						</li>
						<li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                            <input type="text" name="address" id="address" placeholder="请输入你的地址"
                                   value="{% if current_user.address %}{{ current_user.address }}{% else %}{% endif %}" maxlength="10">
						    <i class="error-tips"></i>
                        </li>
						<li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                            <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码"
                                   value="{% if current_user.mobile %}{{ current_user.mobile }}{% else %}{% endif %}" maxlength="10">
                        </li>
                        <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        	<input class="borderno" type="text" name="email" readonly="readonly"
                                   value="{% if current_user.email %}{{ current_user.email }}{% else %}{% endif %}"/>
                            <span class="green changeemai_btn">[修改]</span>
                    	</li>
						<li class="button heibtn">
							<input type="button" id="jsEditUserBtn" value="保存">
						</li>
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
					</ul>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

app/templates/users/usercenter-message.html
{% extends 'users/usercenter-info.html' %}

{% block nav_path %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{{ url_for('index.index') }}">首页</a>></li>
                <li><a href="#">我的消息</a>></li>
                <li>我的消息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_block %}

    <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的消息</h1>
			</div>

		</div>
		<div class="personal_des permessage">
			<div class="head">
				<ul class="tab_header messagehead">
                    <li class="active"><a href="{{ url_for('users.user_messages') }}">个人消息</a></li>
				</ul>
			</div>
			<div class="messagelist">
                {% for message in pagination.get_items %}
                    <div class="messages">
                        <div class="fr">
                            <div class="top"><span class="fl time">{{ message.add_time }}</span><span
                                    class="fr btn foldbtn"></span></div>
                            <p>
                                {{ message.message }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
			</div>

			<div class="pageturn pagerright">
                <ul class="pagelist">
                    <li class="long"
                        style="display:{% if pagination.has_prev %}block{% else %}none{% endif %}">
                        <a href="{{ url_for('users.user_messages',page=pagination.page - 1) }}">上一页</a>
                    </li>
                    {% for p in pagination.iter_pages() %}
                        {% if p %}
                            {% if p==pagination.page %}
                                <li class="active">
                                    <a href="{{ url_for('users.user_messages') }}">{{ p }}</a>
                                </li>
                            {% else %}
                                <li>
                                    <a href="{{ url_for('users.user_messages') }}">{{ p }}</a>
                                </li>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    <li class="long"
                        style="display:{% if pagination.has_next %}block{% else %}none{% endif %}">
                        <a href="{{ url_for('users.user_messages',page=pagination.page + 1) }}">下一页</a>
                    </li>
                </ul>
            </div>
        </div>

    </div>

{% endblock %}

app/templates/users/usercenter-mycourse.html
{% extends 'users/user_base.html' %}

<!--crumbs start-->
{% block nav_path %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{{ url_for('index.index') }}">首页</a>></li>
                <li><a href="#">个人中心</a>></li>
                <li>我的课程</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_block %}
    <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的课程</h1>
			</div>
		</div>
		<div class="personal_des permessage">
			<div class="companycenter">
				<div class="group_list brief">
                    {% for course in pagination.get_items %}
                    <div class="module1_5 box">
                            <a href="{{ url_for('courses.course_detail',course_id=course.id) }}">
                                <img width="214" height="190" class="scrollLoading" src="{{ url_for('static',filename=course.image) }}"/>
                            </a>
                            <div class="des">
                                <a href="{{ url_for('courses.course_detail',course_id=course.id) }}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ course.learn_time }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.courseorg.name }}</span>
                                <span class="star fr  notlogin" data-favid="15">{{ course.courseorg.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="pageturn">
                        <ul class="pagelist">
                            <li class="long"
                                style="display:{% if pagination.has_prev %}block{% else %}none{% endif %}">
                                <a href="{{ url_for('users.user_courses',page=pagination.page - 1) }}">上一页</a>
                            </li>
                            {% for p in pagination.iter_pages() %}
                                {% if p %}
                                    {% if p==pagination.page %}
                                        <li class="active">
                                            <a href="{{ url_for('users.user_courses') }}">{{ p }}</a>
                                        </li>
                                    {% else %}
                                        <li>
                                            <a href="{{ url_for('users.user_courses') }}">{{ p }}</a>
                                        </li>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                            <li class="long"
                                style="display:{% if pagination.has_next %}block{% else %}none{% endif %}">
                                <a href="{{ url_for('users.user_courses',page=pagination.page + 1) }}">下一页</a>
                            </li>
                        </ul>
                    </div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}